[openai]
OPENAI_API_KEY = "pk-CRyEaWebBirhDRupQTxTiAoVwxRWilwuGWhzOedfdhZrEiGw"

[pinecone]
PINECONE_API_KEY = "c840dbb5-36c9-4085-878f-ebbd58ef91a2"
PINECONE_ENVIRONMENT = "mba"
PINECONE_ENDPOINT = "https://us-west4-gcp.api.pinecone.io"
